### ISSUE TITLE
USGS 2019 Hurricane Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris-data-update#56]
The owner of this issue (person who opened it) is responsible for ensuring each task is completed. 
Please reassign issues when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Copy complete dataset collection from USGS FTP site @mitchellryant 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
~~- [ ] Creation of derivative products [hypso and metadata] @ThorTheDestroyer~~
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant
- [x] Update Lidar Selector feature class & downloadable index @mitchellryant
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @mitchellryant
- [x] Update AGO Map to reflect new collection @ThorTheDestroyer

**Twitter**
- [x] Draft Tweet content, link, and image in Comment @ThorTheDestroyer
- [x] Post Tweet @geochik

**Comment by mitchellryant** [comment]
@ThorTheDestroyer  here is the API collection https://api.tnris.org/admin/lcd/collection/6ddcc1e6-2059-4fa2-a2cf-4ab163e2c97e/

**Comment by ThorTheDestroyer** [comment]
@pwblanton Please review the console description. 

This USGS lidar project covers portions of 45 counties in the central to coastal regions of Texas. The acquisition was conducted from January 4, 2019 through February 20, 2019.  Fugro served as the prime contractor for the project and was responsible for planning, acquiring, processing, and producing derivative products of high resolution lidar data(QL2) over the project area. 


Further details regarding this acquisition can be found by downloading the USGS 2019 Hurricane Project Reports.

Points are classified based on the following classifications. 

Class 1 = Unclassified
Class 2 = Bare-Earth Ground
Class 7 = Low Noise
Class 9 = Water
Class 10 = Ignored Ground 
Class 17 = Bridge Decks
Class 18 = High Noise

**Comment by pwblanton** [comment]
This USGS lidar project covers portions of 45 counties in the central to coastal regions of Texas. The acquisition was conducted from January 4, 2019, through February 20, 2019. Fugro served as the prime contractor for the project and was responsible for planning, acquiring, processing, and producing derivative products of high resolution lidar data (QL2) over the project area.

**Comment by pwblanton** [comment]
Hi Joey—

I went into GitHub and made 2 edits and then reassigned to Ryan. Hope that’s right!

Patricia

**Comment by jwhaney** [comment]
> Hi Joey— I went into GitHub and made 2 edits and then reassigned to Ryan. Hope that’s right!

@pwblanton you actually closed the issue just now. I'm guessing you did not mean to do that.

![Screen Shot 2021-03-11 at 2 40 24 PM](https://user-images.githubusercontent.com/13525011/110852284-ca332280-8277-11eb-977f-dcfa6118ed86.png)

**Comment by mitchellryant** [comment]
@ThorTheDestroyer since as of now there is no Hypso data I removed SHP from file types.  but collection has been made public, and issue reassigned to you for completion.

**Comment by ThorTheDestroyer** [comment]
@geochik  Draft Tweet: 

Now available for download, USGS 2019 Hurricane lidar project with new data for portions of central and coastal Texas. 

Are there image constraints I should know with regard to twitter?

**Comment by ThorTheDestroyer** [comment]
@csidenblad the hurricane lidar contours finished finally. they have been placed in \incoming data along with the metadata.
