### ISSUE TITLE
2022 Land Parcels Statewide

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris-data-update#79]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Place data on network or S3 **(QAQC\StratMap\AP_LP\2022)**
- [x] Quality Assurance @LaurenKirk 

**API\data.tnris.org**
- [x] Upload updated data @csidenblad 
- [x] Update Aquistion Date ***(if necessary)*** @csidenblad 
- [x] Update Publication Date ***(if necessary)*** @csidenblad 
	
**Download\Prod**
- [x] Move data to production shares @csidenblad 
- [x] Update Web Service and API collection link(s) ***(if necessary)*** @csidenblad

**Comment by LaurenKirk** [comment]
@mitchellryant @csidenblad   QAQC...**FAILED**
![qaqc_fail](https://user-images.githubusercontent.com/31768897/186257809-b2bf5cf3-b8ef-4b7f-b824-c9bb48bde31a.PNG)
