### ISSUE TITLE
StratMap 2022 50cm Ellis Hill Johnson Navarro Lidar 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/tnris-data-update#83]
**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @ThorTheDestroyer
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @csidenblad
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer

`If zip file is too large (more than 75MB) please let` @csidenblad `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @csidenblad 
- [x] Create Single polygon coverage, by merging all polygons together. @ThorTheDestroyer
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @csidenblad
- [x] Update Lidar Selector feature class & downloadable index @csidenblad
- [x] Make collection public  @csidenblad
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer
- [x] Update AGO Map to reflect new collection @ThorTheDestroyer

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @ThorTheDestroyer
- [ ] Post Tweet @lebell @space-longoria

**Comment by ThorTheDestroyer** [comment]
@csidenblad The supplemental .zip exceed the limit even after removing the control and checkpoint pictures.  Please add the .zip in QAQC/stratmap/lidar/JHEN to the API.

Also please add the items in QAQC/Stratmap/lidar/JEHN/add_to_reports to the reports folder for that collection on the Data drive.

**Comment by ThorTheDestroyer** [comment]
@pwblanton Please review the description at your convenience. 
https://api.tnris.org/admin/lcd/collection/c869398a-326c-4e87-aa54-d1aad28d7ae6/change/

**Comment by pwblanton** [comment]
All looks good!

**Comment by csidenblad** [comment]
@ThorTheDestroyer supplemental has been added and collection made public

**Comment by csidenblad** [comment]
@ThorTheDestroyer just checked on the status of this issue. Are contours still being generated for this collection?

**Comment by ThorTheDestroyer** [comment]
@csidenblad The contours have already been generated. @birdladyellen is moving them to incoming data on our internal server. She'll let you know when they are moved over.

**Comment by csidenblad** [comment]
@birdladyellen were these hypso moved to incomingdata? I see the gmps in there but no shapes? I'm going to start zipping the reclass stuff and will do all three if these are ready to go also

**Comment by birdladyellen** [comment]
@csidenblad I'll check with @ThorTheDestroyer tomorrow but from what I understand everything is there that needs to be. I'm still moving the reclass stuff from my machine to incoming data - it was super slow from home so I'm finishing it up tomorrow in the office.

**Comment by birdladyellen** [comment]
@csidenblad ok yes so I moved the wrong folder. feeling much more confident with command prompt now. I'm going into the office around 10 to move a bunch of stuff over so I'll add this to my list to correct. Also - ignore what I said about the reclass stuff. My mind was thinking of some data I reprojected that I'm also moving today. The reclass stuff is good to go! Apologies

**Comment by birdladyellen** [comment]
@csidenblad the correct SHP files are now in Incoming Data.

**Comment by mitchellryant** [comment]
@birdladyellen need hypso metadata!!

**Comment by birdladyellen** [comment]
On it!

**Comment by birdladyellen** [comment]
@mitchellryant metadata file is complete
