### ISSUE TITLE
South Llano River Topo-Bathy Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris-data-update#84]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @ThorTheDestroyer
- [ ] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @csidenblad
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer

`If zip file is too large (more than 75MB) please let` @csidenblad `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @csidenblad 
- [x] Create Single polygon coverage, by merging all polygons together. @ThorTheDestroyer
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @csidenblad
- [x] Make collection public  @csidenblad
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer
- [ ] Update AGO Map to reflect new collection @ThorTheDestroyer

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @ThorTheDestroyer
- [ ] Post Tweet @lebell @space-longoria

**Comment by csidenblad** [comment]
collection created in API 
https://api.tnris.org/admin/lcd/collection/9298508c-7ff4-43b4-abbe-84f279a5da8e/change/

**Comment by csidenblad** [comment]
@ThorTheDestroyer Ryan mentioned that the last bathy collection was only partially published for download. Just want to confirm that I can publish the full collection.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer 
![image](https://user-images.githubusercontent.com/8459928/195668408-0e8bd460-28ce-4485-8bde-30345e9fca40.png)

**Comment by ThorTheDestroyer** [comment]
@csidenblad yes, publish full collection. Please also upload the supplemental Reports_add-to-api-please.zip that was too large for me to upload. It is located below on the QC drive. 

\stratmap\lidar\southllano

@pwblanton please review the api description.

**Comment by pwblanton** [comment]
I made a few edits.
This StratMap topo-bathy lidar project covers portions of the South Llano River in Edwards and Kimble counties, south of Junction, Texas. This project was managed by the Texas Strategic Mapping (StratMap) Program and utilized the StratMap contracts held by the Texas Department of Information Resources (DIR). Bathymetric Lidar Collection took place January 22, 2022, and topographic lidar was collected on January 25, 2022. Data was collected and processed by Fugro, with third party quality assurance/quality control performed by AECOM. 
 
Lidar acquired from this project will be used for floodplain management and planning, feature extraction, water quality modeling, stream restoration potential analysis, change detection, 9-1-1, wildfire mitigation, and habitat identification/modeling for endangered species.

Points are classified based on the following classifications. 

Class 1: Unclassified
Class 2: Ground
Class 3: Low vegetation
Class 4: Medium vegetation
Class 5: Tall vegetation
Class 6: Buildings
Class 7: Low Point (noise)
Class 9: Water
Class 10: Ignored Ground
Class 14: Culverts
Class 17: Bridges
Class 40: Riverbed
Class 41: Water Surface
Class 45: No Return Found/Noise(Bathymetric Sensor)
Class 46: Ground(Bathymetric Sensor)
