### ISSUE TITLE
USGS 2019 Dallas/Pecos - Update metadata pdf 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/tnris-data-update#88]
Moving issue from previously submitted issue in data.tnris.org repo 
https://github.com/TNRIS/data.tnris.org/issues/58

**Data**
- [x] Reproject contour shapefiles to native projection @birdladyellen @ThorTheDestroyer
- [x] updated metadata pdf/txt provided @birdladyellen 
	
**Download\Prod**
- [x] Sync to s3 @csidenblad 
- [x] Run resources in API 
- [x] confirm updated metadata is available within download @birdladyellen

**Comment by csidenblad** [comment]
@ThorTheDestroyer @birdladyellen Checking in on the status of this issue. Are the contour shps still being reprojected?

**Comment by ThorTheDestroyer** [comment]
@csidenblad I'm still trying to create the 2ft contours for the Hurricane lidar. I believe that it will finish tomorrow, though.  I'll put this next on my GM processing list.  I don't think it will take long to reproject them.

**Comment by birdladyellen** [comment]
@csidenblad I have finished these. Metadata pdf is in the folder as well!
