### ISSUE TITLE
Append new flood buildings to web service

### ISSUE THREAD

**Issue by mpavon** [TNRIS/tnris-data-update#89]
Data append and service refresh needed for Texas Flood Buildings.

@csidenblad the location of the data is at: \\gorgoroth\IncomingData\buildings\output.gdb\TexasFloodBuildings  that needs to be appended to the gdb supporting the service, thanks.

Please update the service once it has the new data appended (only 2,385 buildings this time).

# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**

- [x] Data Processing and Export  [renaming file, data organization] per given naming convention @mpavon
	- Folder Name : 8 digit date YYYYMMDD  EX: 20230112
	- GDB Name: fdst_Buildings_YYYYMMDD 
	- Feature Class Name: TexasFloodBuildings
- [x] Place data on network @mpavon
- [ ] Add data to measures spreadsheet 
- [ ] Quality Assurance @mpavon
	
**Download\Prod**
- [x] Update Web Service @csidenblad
- [ ] Confirm update and close issue @mpavon

**Comment by mpavon** [comment]
@csidenblad Please let me know once the append and refresh tothe TexasFloodBuildings map service happens, so that I can inform USGS. Thanks Chelsea.

**Comment by csidenblad** [comment]
@mpavon I will work on this tomorrow. In the mean time can you please update the naming convention for the data on IncomingData to match what is requested in the issue. 

Folder Name : 8 digit date YYYYMMDD EX: 20230112
GDB Name: fdst_Buildings_YYYYMMDD
Feature Class Name: TexasFloodBuildings

I want all of us to get into the habit of using these naming conventions. It will be necessary as we start to build more automation into our workflows. 

Let me know if you have any questions.

**Comment by csidenblad** [comment]
@mpavon I have appended the new data to TexasFloodBuildings web service. Please confirm you see the added buildings.

**Comment by mpavon** [comment]
@csidenblad I see them, thanks, I am closing the ticket.
