### ISSUE TITLE
USGS Classification Hurricane Pecos Dallas

### ISSUE THREAD

**Issue by birdladyellen** [TNRIS/tnris-data-update#93]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Add data to measures spreadsheet @birdladyellen
- [x] Route Data Shipment [copy data to TNRIS Projects share] @birdladyellen
- [x] Data Processing [renaming file, data organization, data conversion] @birdladyellen
- [x] Quality Assurance @birdladyellen

**API\data.tnris.org**
- [x] Complete API console collection form including metadata and description @birdladyellen 
- [x] Upload supplemental info (breaklines, reports, index) @birdladyellen

`If zip file is too large (more than 75MB) please let` @csidenblad `know and the file can be loaded in another way.`
- [x] Review Description and Formatting @birdladyellen https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @csidenblad 

**Download\Prod**
- [x] Move data to production shares @csidenblad
- [x] Make collection public  @csidenblad
- [ ] Inform TNRIS staff of data availability @birdladyellen

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @birdladyellen
- [ ] Post Tweet @lebell @space-longoria

**Comment by birdladyellen** [comment]
Data is located at port-of-vendors/Fugro/Consolidated_580-22-SOW0016_Central_TX_Delivery/

**Comment by birdladyellen** [comment]
Still waiting on final project level metadata and QC report

**Comment by pwblanton** [comment]
So I don’t have anything to review yet?
Thanks!
Patricia

**Comment by csidenblad** [comment]
@birdladyellen here is an example of how Joey has updated reclassed lidar on the API. 
![image](https://github.com/TNRIS/tnris-data-update/assets/23489372/cea7e776-7306-41e1-951f-41992f57a0cb)

**Comment by mitchellryant** [comment]
@birdladyellen @ThorTheDestroyer are the delivered (S3) indices different from the existing ones?

**Comment by ThorTheDestroyer** [comment]
@mitchellryant They should be the same, but since we only did part of the Dallas Pecos, we might want to add one for that collection, showing the areas that have the additional classifications.

**Comment by birdladyellen** [comment]
@csidenblad handing this off to you

**Comment by csidenblad** [comment]
@birdladyellen Thank Ellen, I will start zipping it when we get back from San Diego. Hope to have it done by 7/21
