### ISSUE TITLE
2023 StratMap Land Parcels

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris-data-update#95]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Add data to measures spreadsheet @LaurenKirk 
- [x] Route Data Shipment [copy data to TNRIS Projects share] @LaurenKirk
- [x] Data Processing [renaming file, data organization]  @LaurenKirk
```
naming convention for shape and fgdb.
stratmap19-landparcels_fipscode_countyname_date.extension
stratmap19-landparcels_48001_anderson_201904.shp
stratmap19-landparcels_48001_anderson_201904.gdb
```
- [x] Quality Assurance @LaurenKirk

**API\data.tnris.org**
- [x] Create API collection @TNRIS/git-sba
- [x] Complete API console collection form including metadata and description @LaurenKirk 
- [x] Upload supplemental info (breaklines, reports, index) @LaurenKirk

`If zip file is too large (more than 75MB) please let` @TNRIS/git-sba `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @LaurenKirk
- [x] Review Description and Formatting @LaurenKirk https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @TNRIS/git-sba 
- [x] Update "Additional County Data" link with new Data Warehouse link for 2023 collection @LaurenKirk 
- [x] Create Single polygon coverage, by merging all polygons together. @LaurenKirk
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba 
- [x] Make collection public  @TNRIS/git-sba

**Twitter**
- [x] Draft X content, link, and image in Comment @LaurenKirk
- [ ] Post X @lebell @space-longoria

**Comment by mitchellryant** [comment]
How many should there be @LaurenKirk ?

**Comment by mitchellryant** [comment]
![image](https://github.com/TNRIS/tnris-data-update/assets/8459928/9c4b6ccc-5c4b-4319-9775-38f1ace15a29)


@LaurenKirk is Eastland good or additional?

**Comment by LaurenKirk** [comment]
> @LaurenKirk exported shp for stratmap23-landparcels_48099_coryell_202301 & corrected mispelling stratmap23-landparcels_48431_sterlilng_202305.shp
> 
> what is the correct date for bandera 202304 or 202301? what is the correct date for dallas 202307 or 202301? what is the correct date for mitchell 202304 or 202301? mitchell also has 2 fgdb what is the correct date for presidio 202304 or 202301? presidio also has 2 fgdb
> 
> see above stratmap23-landparcels_48133_eastland_202301

@mitchellryant  Thanks for exporting and correcting the spelling of the first two items listed!

Correct date for Bandera: 202304
Correct date for Dallas: 202307
Correct date for Mitchell: 202304
Correct date for Presidio: 202304

Eastland should only be in "Additional_County_Data".  Please delete the Eastland fgdb

**Comment by LaurenKirk** [comment]
> How many should there be @LaurenKirk?
> 
> N:\stratmap-2023-land-parcels\fgdb - 225 items N:\stratmap-2023-land-parcels\shp - 222 (shp, cpg, dbf, prj, shx) & 217 (sbn, sbx)
> 
> @LaurenKirk is Eastland good or additional? ![image](https://user-images.githubusercontent.com/8459928/259213621-9c4b6ccc-5c4b-4319-9775-38f1ace15a29.png)

@mitchellryant Not including the counties that fall under "Additional_County_Data" there should be 222 complete land parcel counties. Presumably Mitchell and Presidio's extra fgdb's make up two of the three outliers in the fgdb folder.  Do those two feature classes also have conflicting dates?

**Comment by LaurenKirk** [comment]
All done!
