### ISSUE TITLE
2023 StratMap Address Points

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris-data-update#96]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Add data to measures spreadsheet @LaurenKirk 
- [x] Route Data Shipment [copy data to TNRIS Projects share] @LaurenKirk
- [x] Data Processing [renaming file, data organization]  @LaurenKirk
```
naming convention for shape and fgdb.
stratmap19-addresspoints_fipscode_countyname_date.extension
stratmap19-addresspoints_48001_anderson_201904.shp
stratmap19-addresspoints_48001_anderson_201904.gdb

```
- [x] Quality Assurance @LaurenKirk

**API\data.tnris.org**
- [x] Create API collection @TNRIS/git-sba 
- [x] Complete API console collection form including metadata and description @LaurenKirk 
- [x] Upload supplemental info (breaklines, reports, index) @LaurenKirk

`If zip file is too large (more than 75MB) please let` @TNRIS/git-sba `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @LaurenKirk
- [x] Review Description and Formatting @LaurenKirk https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @TNRIS/git-sba
- [x] Create Single polygon coverage, by merging all polygons together. @LaurenKirk
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/'
	
**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba
- [x] Make collection public  @TNRIS/git-sba

**Twitter**
- [x] Draft X content, link, and image in Comment @LaurenKirk
- [ ] Post X @lebell @space-longoria

**Comment by mitchellryant** [comment]
How many should there be @LaurenKirk ?

**Comment by mitchellryant** [comment]
@LaurenKirk 

since the data has been moved.
i corrected the data on the bexar shp.
& added the data to the medison fgdb
& export the stratmap23-addresspoints_48357_ochiltree_202301 fc to a shp

**Comment by LaurenKirk** [comment]
All done!
